// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccqpjwtzvnvpgmtikwyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjcXBqd3R6dm52cGdtdGlrd3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzMyOTIsImV4cCI6MjA2NTE0OTI5Mn0.Otq7YND4Q7fLxlsu6DjeY_inNO_W53fRWbzy2zbSAwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);